# Generated by Django 4.0.6 on 2022-07-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='fecha',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='titulo',
            new_name='title',
        ),
    ]
